# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fractal-LLM-Course',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/Fractal-LLM-Course',
                'lib_path': 'Fractal_LLM_Course'},
  'syms': {'Fractal_LLM_Course.core': {'Fractal_LLM_Course.core.foo': ('core.html#foo', 'Fractal_LLM_Course/core.py')}}}
